### ISSUE TITLE
possible simpler design?

### ISSUE THREAD

**Issue by streamnsight** [cvallance/mongo-k8s-sidecar#11]
Hello @donbeave @kikov79 @harai @cvallance @ericln ,

Awesome project...
I've been looking at setting up MongoDB with replica sets on Kubernetes, and I found this project, so I'm pretty stoked.

Yet, I'm a little weary of deploying (yet another) NodeJS application in my cluster... It seems a little overkill to run this as a sidecar permanently, so I wanted to pick your brain(s) about another approach:

you've obviously spent a bunch of time on this, so you might just be able to point the flaws in the concept right away before I spend too much time working on it.

Here are the assumptions:
- A replicaSets need to be initialized on the master node, and master node only.
- MongoDB pods are deployed with a ReplicationController, so if a pod dies, it gets replaced, so running a script on post start can check for pods that are gone and pods that came in to reconfigure the master.
- a Headless service provides a list of IPs for the pods references by the mongoDB label.

I'm thinking all this can easily be done with a shell script:
- Looking up pods with the apiserver is just a `curl` command. I use this all the time and use `jq` to parse the JSON output.
- Finding the master (or lack thereof on bootstrap) can be done with the `mongo` shell as command line.

So the idea is the following:
on container lifecycle `postStart` hook, run a shell script in the pod that will:
- lookup IPs of all mongoDB pods.
- run mongo shell `rs.status()` command on each mongo pod to find if there is a master, or an initialized replicaSet already.
  -> if there is a master, list all pods in the replica set from the mongo shell `rs.conf()` command on the master, and add/remove pods according to what the Kubernetes `apiserver` pod list provides.
  -> if there is no master, `rs.initiate()` the current pod as master, and add the other pods as replicas.

Obviously, this could cause problems if a ReplicationController starts many pods at once on bootstrap (race condition to become the master and create the replicaSet)
One could acquire a lock by setting a key in etcd, but that makes things more complicated.
If the process is assumed to bootstrap one mongo pod first, then scale, that seems very reasonable to me.

When a pod dies, the RC will restart it, and reconfig will happen on postStart, so there doesn't seem to need to be a worker running at all times checking the state of the cluster: if a node is gone, it will reconnect, rejoin, and clear up its old IP. 
Left over removed pods may only be a problem on scaling down. A similar reconfig script could be ran on the container lifecycle `preStop` hook.

What are your thoughts?

Cheers

**Comment by cvallance** [comment]
Thanks @streamnsight, I like where you're coming from and agree that it could do with a reevaluation of the current approach.

> One could acquire a lock by setting a key in etcd, but that makes things more complicated.

I don't mind adding complexity like this as long as we abstract it away from the user of the sidecar, it's a much more elegant than the shared algorithm to pick a master we currently have. 

> If the process is assumed to bootstrap one mongo pod first, then scale, that seems very reasonable to me.

I wouldn't want to put a requirement like this onto the user. Again, if we can deal with the complexity ourselves without exposing it to the users, all the better.

I'd be a little apprehensive to rely completely on `postStart` and `preStop` scripts... there should also be some kind of health check that happens on a regular interval so if the RS or kubernetes gets in a weird state, it will repair itself. The `postStart` script could possibly fill this role. Also, if this is going to be a script, I'd assume you'd create a cronjob to run the health check? If so, the minimum cronjob interval is 1 minute, would that be ok?

We're also making the assumption that we can connect to the master from any of the nodes to do the job of adding and removing nodes. Is that a safe assumption? Could the credentials be different?

Those are my initial thoughts.

Again, I like where you are coming from... another approach would be to rewrite this project incorporating some ideas from this (`postStart` + `preStop` + `healthCheck` scripts and acquiring a lock for master election) but create some lightweight binary (golang springs immediately to mind) running on a bare minimum base image... basically making it as lightweight as possible.

**Comment by streamnsight** [comment]
@cvallance 
I started working on this and here is what I find:
- `postStart` script start as soon as the container is running, which does not guarantee mongo is running, so I had to check that I can reach it. Not a big deal, but good to know.
- the pod is not registered with the **Service** until the pod is in `ready` state, which means the pod getting started doesn't show on the list when listing the pods referenced by the Service. Again, since this is consistent, that is not a big deal: I just had to add the starting pod to the list.

Regarding your comments:
Considering the fact that the Service doesn't register the pods until done with `postStart`, if several pods are deployed at once on bootstrap, pods can't know if another pod is in the cluster. So some kind of lock would be necessary. Accessing etcd directly is an option, but frankly, as soon as you use TLS on etcd, it becomes a pain, and running a separate etcd instance for this sounds overkill too (and it could be partitioned and so many other things could happen)

For now i have things running by bootstrapping with one node, then scaling. Yes I can see how it can be dangerous too (like if you replace your RC and forgot the `replica` number is 1 and all your other pods get terminated...)

regarding healthchecks:

I understand healthchecks are nice to have, but what would you do?
Mongo already takes care of flagging pods that are unhealthy in its cluster and handles that well as far as I know. If a node is permanently gone, that's when you want to remove it.
I have had `preStop` fail and not remove the node from the cluster, but `postStart` does cleanup too, so as soon as the pod is replaced things go back to normal.

>  if the RS or kubernetes gets in a weird state,
I think you have bigger problems that a healthcheck won't help with.

You can run a command or http probe as a readiness probe if you wanted to do a healthcheck. 
When not ready the pod will be removed from the Service and won't be served traffic. After a number of failures the pod will be restarted. That seems like all you really need.

A command based healthcheck could run a script too and do other stuff, although again I'm not sure what you would do at that point.

I guess the biggest problem in all this may be a network partition. In that case I feel like it may just be best to let Mongo deal with it: removing pods because they were partitions momenterally may do more harm than good.

**Comment by allanlei** [comment]
> If the process is assumed to bootstrap one mongo pod first, then scale, that seems very reasonable to me.

[PetSets](http://kubernetes.io/docs/user-guide/petset/) should be able to help with this. 
> Create one pet at a time, in order from {0..N-1}, and wait till each one is in Running and Ready before creating the next

**Comment by streamnsight** [comment]
i implemented the poststart, prestop idea and it works fine. all in shell.

now, with k8s 1.3.4 there are now `init` containers, and that is prbably the way to go. in the future.

will look into porting my scripts to init containers once i upgraded my cluster

**Comment by streamnsight** [comment]
and yes otherwise PedSets are another way to have a more stable IP assignment but the init still has to be done.

**Comment by streamnsight** [comment]
PS: here are the scripts I use:

https://gist.github.com/anonymous/4b74dabf9343ae2d146a60f3c1a0815e
https://gist.github.com/anonymous/9306d830fd97aabd0484b97bb1a50d3e

**Comment by cvallance** [comment]
Closing this as an issue.
