### ISSUE TITLE
Azure Storage Account not found- "vhds" container necessary.

### ISSUE THREAD

**Issue by MathiasVandePol** [cvallance/mongo-k8s-sidecar#18]
Hey.

I was implementing your example and noticed that it failed because it could not find the azure storage account.
Some digging showed that the vhds container is necessary. Perhaps it is good to add this in your readme.md

More info [here](https://github.com/kubernetes/kubernetes/issues/38362)

**Comment by tomerf** [comment]
Hi Mathias,

I just encountered the same issue, it is a kubernetes bug (actually fixed 3 days before you posted it!). You can upgrade kubernetes or create the container manually.
I don't think it's needed to document it in every project that use Azure storage class.
