### ISSUE TITLE
Does not work well with stateful sets.

### ISSUE THREAD

**Issue by jwaldrip** [cvallance/mongo-k8s-sidecar#20]
I have pods that are in a removed state from the replica set. this leaves the cluster in an unusable state. Why doesn't the sidecar automatically remove these nodes?

**Comment by cvallance** [comment]
The sidecar uses a pod label selector to get the pods that should be in the replica set... nothing to do with a replica set or stateful set... so if you have pods that match the selector that are still running, they won't get removed.

Maybe you could change the labels for pods that are removed from the stateful set and/or replica set?

PR welcome if you want to have a go at trying to use something other than pod label selectors.

**Comment by cvallance** [comment]
@jwaldrip - did I understand your question / issue correctly?

**Comment by cvallance** [comment]
@jwaldrip - I'm going to close this issue because I haven't heard anything back from you. Please re-open if you feel it should be.
