### ISSUE TITLE
is there any way to connect from robomongo /  mongochef

### ISSUE THREAD

**Issue by knsakib** [cvallance/mongo-k8s-sidecar#22]
Google container engine gives internal of mongo service(which is fine). However, Is there any way to connect to that mongodb through robomongo / mongochef ?

**Comment by cvallance** [comment]
I'm able to connect to my replica set in AWS (using Tectonic) via a simple ssh tunnel. Mongochef supports that kind of setup.

Can you do anything like that yourself?

**Comment by cvallance** [comment]
I'm going to close this issue because it isn't directly related to this github project.

More than happy to offer help @knsakib - let me know if you have any other questions or comments.
