### ISSUE TITLE
Memory leak on node process

### ISSUE THREAD

**Issue by fschuh** [cvallance/mongo-k8s-sidecar#30]
I was testing this sidecar container on a Kubernetes cluster made up of 3 small nodes, and noticed one of my nodes became unresponsive.
After examining the processes, I found a node.js process that belongs to mongo-k8s-sidecar taking 1 GB of memory, which caused other critical processes to crash.

Here's the output from top:

```
  PID	USER	PR	NI	VIRT	RES	SHR	S	%CPU	%MEM	TIME+		COMMAND                                                                                                                                         
10498	1001	20	0	1565688	0.999g	0	D	0.2	51.1	1:36.21		node                                                                                                                                            
 3673	root	20	0	731068	95792	0	S	0.8	4.7	12:48.00	mongod                                                                                                                                          
 2754	root	20	0	675800	74988	0	S	0.4	3.7	10:58.94	mongod                                                                                                                                          
26246	root	20	0	666336	74184	0	S	0.4	3.6	10:22.46	mongod       
```

Output from ps shows this:

`3372 ?        Sl     0:00 node /opt/cvallance/mongo-k8s-sidecar/node_modules/.bin/forever src/index.js`

This happened after about 1 full day of running the Mongo pods that contain this sidecar inside.
It happens consistently, and after a third occurrence I came here to report the issue.
I didn't set any resource limits on the sidecar container, as I had no idea the memory use could spike this high for such a small helper program.

**Comment by fschuh** [comment]
I'm sorry, this was a total misunderstanding on my side.
It was not caused by this sidecar container, it was another node.js process in another Pod.
I didn't look at the PID number close enough.

Sorry for the confusion, please disregard this issue.

**Comment by cvallance** [comment]
*phew*
