### ISSUE TITLE
How to access mongodb server with statefulset from outside k8S cluster?

### ISSUE THREAD

**Issue by luckyfengyong** [cvallance/mongo-k8s-sidecar#32]
Any idea how external user access mongodb service?
I try to export the mongodb as a normal service, for example, the type of NodePort. I could access mongodb by CLI or programming interface but has to specify rs.slaveOk(). However according to http://dbversity.com/mongodb-why-we-need-to-set-rs-slaveok-while-querying-on-secondaries, the rs.slaveOk() may not be recommended for all the use cases. 
Does user has to use the old solution of one replicateset/service per mongodb instance?
BTW, the service has to be created with headless first, otherwise sidecare failed to initialize mongodb instance. User could update the service with nodeport or other type later to access the mongodb externally.

**Comment by luckyfengyong** [comment]
@cvallance @thesandlord 
Could you please shed some light on it?
Thanks

**Comment by luckyfengyong** [comment]
Forget to run rs.initiate(). After that, mongoimport works but only with primary node. However from outside K8S cluster, it will be hard to identify the primary node and access it. I have to create a service with the endpoint of hard coded ip address of primary node.

**Comment by luckyfengyong** [comment]
Correct above. Just aware, the service has to be created with headless first, otherwise sidecare failed to initialize mongodb instance. User could update the service with nodeport or other type later to access the mongodb externally.

**Comment by cvallance** [comment]
What's the use case for accessing it externally? I.e. is it an app accessing it externally OR are you simply trying to connect via mongo chef or robomongo to debug or run some queries?

**Comment by luckyfengyong** [comment]
@cvallance We want to offer mongo as a service on our private kube cloud and the developer may be using this service from an application on their own environment (may not be kube or even docker). We need to be able to access mongo from external apps and tools like Mongo Compass.

**Comment by neverfox** [comment]
@luckyfengyong You would do it like you would any other k8s service you wanted to expose outside the cluster, e.g. create a LoadBalancer service. Nothing prevents you from having more than one service pointing to the pods.

**Comment by prateekrastogi** [comment]
@neverfox While connecting with loadbalancer using type loadbalancer and assigning an external ip, it starts to give out no primary found error using mongodb client connector. Even changing the connection url optional parameters to allow read from secondary is not allowing it to connect properly. The same issue persist while using NodePort too. But, inside the kubernetes cluster it is happening properly with the same connector. 
@cvallance How can we use tools like mongodb compass in such cases? I think the main issue is regarding forming a valid connection url for connecting with external ip addresses

**Comment by pashok2398** [comment]
Hi i used this:
Label each pod with its name:
```
 kubectl label pod mongo-0 mongoInst=0
 kubectl label pod mongo-1 mongoInst=1
 kubectl label pod mongo-2 mongoInst=2
```
Expose each pod individually:
```
kubectl expose pod mongo-0 --name mongo-0 --type NodePort
kubectl expose pod mongo-1 --name mongo-1 --type NodePort
kubectl expose pod mongo-2 --name mongo-2 --type NodePort
```
Now you can access the NODE_NAME:NodePort

**Comment by mallikharjunrao** [comment]
@pashok2398 i tried connecting NODE_NAME:port and PUBLIC_IP_OF_NODE:port doesnt work for me. is DNS_NAME_OF_NODE:port works?

**Comment by prakashechidna** [comment]
@luckyfengyong , did you solve this issue?

**Comment by pavanpaik** [comment]
@cvallance  Do you have a resolution for this issue?

**Comment by cvallance** [comment]
@pavanpaik - Did the approach @pashok2398 outlined not work for you? Where is it hosted? If it's hosted on a cloud provider, there might be some additional things you need to do... e.g. create a service per pod and make it `LoadBalancer` or create some security rules to allow traffic on the ports that your opening on your nodes.

This really isn't a question about the sidecar but more of question of how to expose pods / services in general.

**Comment by bambrozio** [comment]
Wondering if anyone solves this out... 
I'm facing the same issue. Did someone manage to expose mongo outside k8s cluster?

**Comment by bambrozio** [comment]
Nevermind - Get it working by simply performing:
```
kubectl expose svc mongo --name mongo-client --type NodePort
```
Thus I could connect by:
```
~/Downloads/mongodb-osx-x86_64-4.0.5/bin/mongo --host localhost:30320
```
as `30320` was the port assigned to my new service `mongo-client`
