### ISSUE TITLE
How to use different storage classes for StatefulSet example

### ISSUE THREAD

**Issue by Globegitter** [cvallance/mongo-k8s-sidecar#33]
I am followed the blog http://blog.kubernetes.io/2017/01/running-mongodb-on-kubernetes-with-statefulsets.html on Azure and all working well, but how can I connect the different replicas of the mongo `StatefulSet` to different storage classes? Right now every replica connects to the same storage class / storage account in Azure, so if there are any issues with that account it can affect the whole replica set

Not sure if here is the right place to create the issue - maybe that is something for the Kubernetes repo itself. Just let me know.

**Comment by markfejes** [comment]
I believe you can achieve this by creating x more storage classes for different storage accounts. 
The documentation says, that you can specify a storage account in the storage class definition
[Azure Storage Class](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#azure-disk)

Sorry if I misunderstood your question!

**Comment by cvallance** [comment]
This is a limitation of the `StatefulSet` in that you can only apply a single volume claim.

You could have two different `StatefulSet`s and have different volume claims for each one. The way the sidecar works is that it calls the k8s api to get all the pods that should be in the replicaset using the value you set in `MONGO_SIDECAR_POD_LABELS` ... so as long as the two `StatefulSet` definitions share the same labels you have in that environment variable, they should all be included in the replicaset configuration.
