### ISSUE TITLE
Synergies

### ISSUE THREAD

**Issue by YouriT** [cvallance/mongo-k8s-sidecar#35]
I think there might be some interesting synergies to do with this [helm mongodb-replicaset](https://github.com/kubernetes/charts/tree/master/stable/mongodb-replicaset) incubator project.

Any thoughts about this?

_Edit: Link updated_

**Comment by sibelius** [comment]
@YouriT the link is broken

**Comment by YouriT** [comment]
Mmh strange something changed!

Le 22 avr. 2017 13:21, "Sibelius Seraphini" <notifications@github.com> a
écrit :

**Comment by YouriT** [comment]
It switched to stable branch : https://github.com/kubernetes/charts/tree/master/stable/mongodb-replicaset

**Comment by sibelius** [comment]
looks good tks

**Comment by cvallance** [comment]
Interesting project, loads of good stuff in there. If I had some time I'd check it out to see if there was some synergies.

I suspect there isn't given that they take a different approach... i.e. setting up the replica set as part of bootstrapping the whole pod / stateful set.
