### ISSUE TITLE
Ability to work with secured databases needed

### ISSUE THREAD

**Issue by abinet** [cvallance/mongo-k8s-sidecar#38]
First of all I like the sidecar approach you are using in opposite to creating hard roled instances like https://github.com/bitnami/bitnami-docker-mongodb does.

But I miss an ability to config the databases with enabled security. Thus I made a small extension to get it work (see my PR)

**Comment by YouriT** [comment]
To have a link between both: #39

**Comment by cvallance** [comment]
Fixed with #39
