### ISSUE TITLE
Transitioning from existing standalone / rs

### ISSUE THREAD

**Issue by BeHiz** [cvallance/mongo-k8s-sidecar#49]
Hi All,
My apologies if this is the wrong place to write a question.

I need to transition an existing standalone to mongo-k8s-sidecar.  Mongo [offer this procedure](https://docs.mongodb.com/manual/tutorial/convert-standalone-to-replica-set/). 

Can this procedure be followed with sidecar?

**Comment by cvallance** [comment]
You could transition from existing to a mongo-k8s-sidecar. How you would do that depends on a large number of variables around your own setup. Happy to continue to discuss but will be closing this issue.
