### ISSUE TITLE
StatefulSets example: Four MongoDB Warnings 

### ISSUE THREAD

**Issue by BeHiz** [cvallance/mongo-k8s-sidecar#50]
Hi,

The StatefulSets example, when run exactly as described in the [readme](https://github.com/cvallance/mongo-k8s-sidecar/blob/master/example/StatefulSet/README.md), 
shows the following warnings (when connecting to _mongo shell_).

please, which of these should be taken seriously and how can they be avoided?

```
** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
**          See http://dochub.mongodb.org/core/prodnotes-filesystem

** WARNING: Access control is not enabled for the database.
**          Read and write access to data and configuration is unrestricted.
** WARNING: You are running this process as the root user, which is not recommended.


** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
**        We suggest setting it to 'never'
```

**Comment by pkdone** [comment]
See: http://pauldone.blogspot.co.uk/2017/06/mongodb-kubernetes-production-settings.html
