### ISSUE TITLE
Username and Password variables

### ISSUE THREAD

**Issue by BeHiz** [cvallance/mongo-k8s-sidecar#51]
A question please:

Do the environment variable MONGODB_USERNAME & MONGODB_PASSWORD have any affect after the first deployment? is changing them a good way of changing admin password or should that be done through interacting with mongo directly?

(if this is not the appropriate place for questions, I do apologize)

**Comment by pkdone** [comment]
See: http://pauldone.blogspot.co.uk/2017/06/deploying-mongodb-on-kubernetes-gke25.html

**Comment by cvallance** [comment]
No. In fact, as far as the sidecar is concerned, it doesn't have any effect... I.e. it simply uses them for authentication with the mongodb instance, it doesn't set them or anything like that... that's up to the user to do themselves.
