### ISSUE TITLE
MongoError: Found two member configurations with same host field

### ISSUE THREAD

**Issue by allansene** [cvallance/mongo-k8s-sidecar#52]
Hi, guys! 

We just deployed some mongo replicas on our cluster, but some mongo-sidecar instances are returning this error below:

```
Error in workloop { MongoError: Found two member configurations with same host field, members.0.host == members.2.host == 10.32.2.59:27017
    at Function.MongoError.create (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/error.js:31:11)
    at /opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:489:72
    at authenticateStragglers (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:435:16)
    at Connection.messageHandler (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:469:5)
    at Socket.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/connection.js:321:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
```

We have pairs of 2 Mongo Instances on each service and one of those says on Mongo Console with the label SECONDARY and the other with the label OTHER (status REMOVED from `rs.conf()`). Our Mongo Servers is v3.4.6.

Our Kubernetes is on GKE:

```
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.1-gke.0", GitCommit:"841411e511bfb1ccd78e76bf8633d4515061e18b", GitTreeState:"clean", BuildDate:"2017-07-14T17:52:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

Anyone knows what could be occasioning these errors? Thanks!

**Edit**: I think that is happening some conflict on the election for the PRIMARY. As the [documentation says](https://docs.mongodb.com/manual/core/replica-set-elections/#replica-set-non-voting-members), we must have, at least, 3 replicas for voting.

**Comment by TrafeX** [comment]
We're running into the same issue. We have 3 Mongo instances and it happend when we changed the updateStrategy from the default `OnDelete` to `RollingUpdate`.
Now this is the output of the sidecar:

```
Invalid set, re-initializing
replSetReconfig { _id: 'rs0',
  version: 8,
  protocolVersion: 1,
  members: 
   [ { _id: 0,
       host: '10.8.6.58:27017',
       arbiterOnly: false,
       buildIndexes: true,
       hidden: false,
       priority: 1,
       tags: {},
       slaveDelay: 0,
       votes: 1 },
     { _id: 2,
       host: '10.8.0.94:27017',
       arbiterOnly: false,
       buildIndexes: true,
       hidden: false,
       priority: 1,
       tags: {},
       slaveDelay: 0,
       votes: 1 },
     { _id: 3, host: '10.8.6.144:27017' },
     { _id: 4, host: '10.8.3.230:27017' },
     { _id: 5, host: '10.8.0.94:27017' } ],
  settings: 
   { chainingAllowed: true,
     heartbeatIntervalMillis: 2000,
     heartbeatTimeoutSecs: 10,
     electionTimeoutMillis: 10000,
     catchUpTimeoutMillis: 60000,
     getLastErrorModes: {},
     getLastErrorDefaults: { w: 1, wtimeout: 0 },
     replicaSetId: 599d9c18a06edd8d07807c03 } }
Error in workloop { MongoError: Found two member configurations with same host field, members.1.host == members.4.host == 10.8.0.94:27017
    at Function.MongoError.create (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/error.js:31:11)
    at /opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:489:72
    at authenticateStragglers (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:435:16)
    at Connection.messageHandler (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/pool.js:469:5)
    at Socket.<anonymous> (/opt/cvallance/mongo-k8s-sidecar/node_modules/mongodb-core/lib/connection/connection.js:321:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
  name: 'MongoError',
  message: 'Found two member configurations with same host field, members.1.host == members.4.host == 10.8.0.94:27017',
  ok: 0,
  errmsg: 'Found two member configurations with same host field, members.1.host == members.4.host == 10.8.0.94:27017',
  code: 103,
  codeName: 'NewReplicaSetConfigurationIncompatible' }
```

@allansene How did you fix this?

**Comment by PanJ** [comment]
I have 3 nodes and facing this problem as well.

**Comment by bsomogyi** [comment]
I'm facing this issue as well (using a statefulset and I"m using the stable network pod ID for my replicas in the sidecar).  Anyone have luck with this issue or have a workaround?

**Comment by firefoxNX** [comment]
Same here. Tried restarting the pods (delete) still the same error

`Error in workloop { MongoError: Found two member configurations with same host field, members.0.host == members.1.host == mongo-0.mongo.ns.svc.cluster.local:27017`

**Comment by allansene** [comment]
@TrafeX I just added more Mongo containers' on the pod, 3 in total. I don't remember changing another configuration. Don't know how to help you :(

**Comment by firefoxNX** [comment]
k8s newbie here... do we have to create a service for each mongo node by running `kubectl expose pod mongo-0 --name mongo-0 --type NodePort --namespace=ns`?

**Comment by bsomogyi** [comment]
@allansene - I'm curious as to what version of mongo you are running?  I've tried both 3.4 and 3.5 and encountered the issue. Wondering if its potentially related to the version of mongo some of us are running.

**Comment by bsomogyi** [comment]
I ended up adding the following to the mongo.js addNewMembers function in my Fork so only members that don't exist get added to the replicaset config. Seemed to have solved the problem for me.  If it solves the problem for others I can open a PR. Suspect there is a race condition occuring between the initialization and addition of new members.

`    var exists = false;

    for (var j in rsConfig.members) {
      var member = rsConfig.members[j];
      if (member.host === addrsToAdd[i]) {
        console.log("Host [%s] already exists in the Replicaset. Not adding...",addrsToAdd[i])
        exists = true
        break;
      }
    }

    if (!exists){
      rsConfig.members.push(cfg);
    `

**Comment by fega** [comment]
@bsomogyi I'd want to add this first to my fork but I'm a little bit confused of where your code should be place, could you share your addNewMembers function?

thanks

**Comment by igorrendulic** [comment]
I had the same problem.

While trying implement a solution i got familiar with code a bit and decided it's not a good solution for me. It's constantly updating replica set configurations in a loop which feel dangerous in the long run. 

To solve the problem i removed mongo k8s sidecar from my `statefulset` and manually forced new replica set configuration: 

```
rs.reconfig({_id: "rs0", version: 1, members: [
       { _id: 0, host : "mongo-0.mongo.default.svc.cluster.local:27017" },
       { _id: 1, host : "mongo-1.mongo.default.svc.cluster.local:27017" },
       { _id: 2, host : "mongo-2.mongo.default.svc.cluster.local:27017" }

 ]}, {force:true});
```

This is ok for testing but for something more serious i think scripts would be required where replica set could be configured based off of environment parameters.

**Comment by cvallance** [comment]
Implemented fix as mentioned by @bsomogyi ... feel free to re-open if you see this issue happening again.
