### ISSUE TITLE
rs.initiate() must be triggered manually on all mongo pods of the set

### ISSUE THREAD

**Issue by nottinhill** [cvallance/mongo-k8s-sidecar#57]
In essence the stateful set is failling to configure.

**Comment by aliartiza75** [comment]
@meshfields how did you resolved this issue?

**Comment by meshfields** [comment]
I stopped using Sidecars alltogether. None of them worked for us.


Am 6. Mai 2019 um 08:26:26, Irtiza Ali (notifications@github.com) schrieb:

@meshfields how did you resolved this issue?

**Comment by aliartiza75** [comment]
@meshfields then how are you creating MongoDB statefulsets in k8s?

**Comment by meshfields** [comment]
Sorry to not be of help here but we offshored all DataBase into the Propietery Cloud due to the parameters of the project. I know its bad.


Am 6. Mai 2019 um 12:09:17, Irtiza Ali (notifications@github.com) schrieb:

@meshfields then how are you creating MongoDB statefulsets in k8s?

**Comment by aliartiza75** [comment]
@meshfields thank you.

**Comment by aliartiza75** [comment]
@meshfields this issue will not raise if you use [mongodb helm chart](https://github.com/helm/charts/tree/master/stable/mongodb)
