### ISSUE TITLE
Did anybody ever manage to set this up?

### ISSUE THREAD

**Issue by meshfields** [cvallance/mongo-k8s-sidecar#60]
I am trying for 2 weeks now, but 

Unhandled rejection MongoError: failed to connect to server [mongo-0:27017] on first connect [MongoError: getaddrinfo ENOTFOUND mongo-0 mongo-0:27017]

is the only outcome I get. I tried

mongo-0
mongo-0.default.svc.cluster.local
mongo-0.mongo.default.svc.cluster.local

I have set

        - name: KUBERNETES_MONGO_SERVICE_NAME
          value: mongo

**Comment by cvallance** [comment]
What do your service definitions look like? How are you setting up your mongo instances? StatefulSet or manual ReplicationControllers?

**Comment by cmosgh** [comment]
@nottinhill 
you can add some labels to your mongo instances i.e.: 
replSet: someReplSet

and then use 
`env:
    - name: MONGO_SIDECAR_POD_LABELS
       value: replSet=someReplSet`
for the sidecar

**Comment by yoshz** [comment]
Just had the same issue. 
Seems like the mongo:3.6 docker image listens on address 127.0.0.1. From mongo logs:
```
WARNING: This server is bound to localhost.
         Remote systems will be unable to connect to this server. 
         Start the server with --bind_ip <address> to specify which IP 
         addresses it should serve responses from, or with --bind_ip_all to
         bind to all interfaces. If this behavior is desired, start the
         server with --bind_ip 127.0.0.1 to disable this warning.
```
