### ISSUE TITLE
Authentication failed with replica set mongodb kubernetes

### ISSUE THREAD

**Issue by viniciusks** [cvallance/mongo-k8s-sidecar#89]
# Description

Before I had just a mongodb pod with simple authentication (username and password), today I needed to perform the mongo replica set to increase mongo's performance.

Today my mongo structure is like this:
mongo-0 - primary
mongo-1 - should be the secondary

But mongo-1 gives authentication failure.
How would I configure my mongo statefulset to accept this authentication?

# Code

> apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 2
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: ootz/ootz_mongo:3.6
          command:
            - mongod
          args:
            - "--replSet"
            - rs0
            - "--bind_ip"
            - 0.0.0.0
            - "--auth"
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          resources:
            limits:
              cpu: 1100m
            requests:
              cpu: 1100m
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar:latest
          resources:
            limits:
              cpu: 50m
            requests:
              cpu: 20m
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
            - name: MONGODB_USERNAME
              value: "username"
            - name: MONGODB_PASSWORD
              value: "password"
            - name: MONGODB_DATABASE
              value: "admin"
      nodeSelector:
        purpose: db
  volumeClaimTemplates:
    metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

**Comment by CurosMJ** [comment]
https://github.com/cvallance/mongo-k8s-sidecar/pull/86 Try using this PR's updated spec

**Comment by viniciusks** [comment]
Thank you, I've already resolved

**Comment by mau21mau** [comment]
@viniciusks How did you solved the issue?

**Comment by viniciusks** [comment]
@mau21mau I followed this example. 
https://gist.github.com/thilinapiy/0c5abc2c0c28efe1bbe2165b0d8dc115
